In [9]:
import numpy as np
import pandas as pd
import time

Question 1: Write a function for Multiple Linear Regression. 

In [10]:
def Multi_L_reg(A, y):
    start_time = time.time()
    A = np.asmatrix(A)
    A = np.insert(A, 0, 1, axis=1)
    y = np.asmatrix(y).T
    #beta = np.dot(np.linalg.inv(np.dot(A.T, A)),A.T)
    beta = ((A.T * A).I) * A.T
    beta = np.dot(beta, y)
    #print(A.shape, y.shape)
    end_time = time.time()
    print("time usage in Linear reg: ", end_time-start_time)
    return beta

This is the Linear regression method

In [11]:
a =np.array([[1,2,1,3],[2,2,1,2],[3,4,1,2],[7,8,3,9]])
y=np.array([2,1,2,8])

res = Multi_L_reg(a,y)
print(res)

time usage in Linear reg:  0.0009982585906982422
[[  22.25]
 [  27.  ]
 [   0.75]
 [-106.  ]
 [  18.5 ]]


In [12]:
a = np.mat([[1,2,5],[3,4,6]])

print(a.shape[1])

b = np.asmatrix(np.random.rand(a.shape[1],1))

print(b)

3
[[0.57591505]
 [0.63411718]
 [0.30985924]]


Question 2: Write a gradient based method to optimzie the solution and compare the time consumption between the two methods with different scales of input. 

In [13]:
def Gradient_descent(A, y):
    start_time = time.time()
    A = np.asmatrix(A)
    A = np.insert(A, 0, 1, axis=1)
    beta_size = A.shape[1]
    y = np.asmatrix(y).T
    
    beta = np.asmatrix(np.random.rand(beta_size, 1))
    #print(beta)
    alpha = 0.01
    K = 10000
    for i in range(K):
        beta = beta - alpha*((A.T * A)*beta - A.T*y)
    end_time = time.time()
    print("time usage in Gradient descent: ", end_time-start_time)
    return beta

In [14]:
a =np.array([[1],[2],[3],[4]])
y=np.array([2,4,6,8])

res = Gradient_descent(a,y)
print(res)

time usage in Gradient descent:  0.3435664176940918
[[8.4293581e-15]
 [2.0000000e+00]]


In [15]:
def timer_func(input_func, args):
    start_time = time.time()
    input_func(args[0], args[1])
    end_time = time.time()
    return end_time-start_time

print("time usage in timer_func: ", timer_func(Gradient_descent, [a,y]))

time usage in Gradient descent:  0.25478172302246094
time usage in timer_func:  0.25478172302246094
